services:
  compiler-engine:
    container_name: compiler-engine
    image: registry.gitlab.ti.bfh.ch/internetofsoils/infrastructureforsensormanagment/compiler-engine:${TAG}
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - compiler-engine-source:/source
      - compiler-engine-output:/output
      - compiler-engine-logs:/logs
      - compiler-engine-cache:/cache
    env_file:
      - .env
  compiler-engine-cleaner:
    image: registry.gitlab.ti.bfh.ch/internetofsoils/infrastructureforsensormanagment/compiler-engine-cleaner:${TAG}
    container_name: compiler-engine-cleaner
    volumes:
      - compiler-engine-source:/source
      - compiler-engine-output:/output
      - compiler-engine-logs:/logs
      - ./src/compiler-engine/app/cleaner.py:/app/cleaner.py
    env_file:
      - .env
    restart: unless-stopped
  reverse-proxy:
    image: registry.gitlab.ti.bfh.ch/internetofsoils/infrastructureforsensormanagment/reverse-proxy:${TAG}
    container_name: reverse-proxy
    restart: unless-stopped
    cap_add:  # improve QUIC speeds
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - reverse-proxy-data:/data
      - reverse-proxy-config:/config

  webapp-backend:
    image: registry.gitlab.ti.bfh.ch/internetofsoils/infrastructureforsensormanagment/webapp-backend:${TAG}
    container_name: webapp-backend
    restart: unless-stopped
    ports:
      - "8001:8000"
    environment:
      - TRIPLESTORE_ENDPOINT=http://fuseki:3030/testing
      - PYTHONUNBUFFERED=1
    env_file:
      - .env-backend
  fuseki:
    image: stain/jena-fuseki:5.1.0
    container_name: fuseki-triplestore
    restart: unless-stopped
    ports:
      - "3030:3030"
    volumes:
      - fuseki-data:/fuseki
    environment:
      - ENABLE_DATA_WRITE=true
      - ENABLE_UPDATE=true
      - ENABLE_SHACL=false # Used for rdf-structure validation
      - TDB=2
      - FUSEKI_DATASET_1=core # Creates empty dataset with given name
      - FUSEKI_DATASET_2=testing
    env_file:
      - .env-fuseki
volumes:
  reverse-proxy-data:
  reverse-proxy-config:
  compiler-engine-source:
    name: compiler-engine-source
  compiler-engine-output:
    name: compiler-engine-output
  compiler-engine-logs:
    name: compiler-engine-logs
  compiler-engine-cache:
    name: compiler-engine-cache