services:
  compiler-engine:
    container_name: compiler-engine
    build:
      context: src/compiler-engine
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - compiler-engine-source:/source
      - compiler-engine-output:/output
      - compiler-engine-logs:/logs
      - compiler-engine-cache:/cache
    env_file:
      - .env
  volumes-cleaner:
    build:
      context: src/volumes-cleaner
      dockerfile: Dockerfile
    container_name: volumes-cleaner
    volumes:
      - compiler-engine-source:/source
      - compiler-engine-output:/output
      - compiler-engine-logs:/logs
      - ./src/compiler-engine/app/cleaner.py:/app/cleaner.py
    env_file:
      - .env
    restart: unless-stopped

  reverse-proxy:
    image: caddy:2.9.1
    container_name: reverse-proxy
    restart: unless-stopped
    cap_add:  # improve QUIC speeds
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./config/reverse-proxy/conf:/etc/caddy
      - ./src/webapp-frontend/www:/srv
      - ./config/reverse-proxy/_data:/data
      - ./config/reverse-proxy/_config:/config
      # - ./config/reverse-proxy/certs:/certs

volumes:
  compiler-engine-source:
    name: compiler-engine-source
  compiler-engine-output:
    name: compiler-engine-output
  compiler-engine-logs:
    name: compiler-engine-logs
  compiler-engine-cache:
    name: compiler-engine-cache