services:
  compiler-engine:
    container_name: compiler-engine
    build:
      context: src/compiler-engine
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - compiler-engine-source:/source
      - compiler-engine-output:/output
      - compiler-engine-logs:/logs
      - compiler-engine-cache:/cache
    env_file:
      - .env
  volumes-cleaner:
    build:
      context: src/volumes-cleaner
      dockerfile: Dockerfile
    container_name: volumes-cleaner
    volumes:
      - compiler-engine-source:/source
      - compiler-engine-output:/output
      - compiler-engine-logs:/logs
      - ./src/compiler-engine/app/cleaner.py:/app/cleaner.py
    env_file:
      - .env
    restart: unless-stopped
  reverse-proxy:
    build:
      context: .
      dockerfile: src/webapp-frontend/Dockerfile
    container_name: reverse-proxy
    restart: unless-stopped
    cap_add:  # improve QUIC speeds
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - reverse-proxy-data:/data
      - reverse-proxy-config:/config
  webapp-backend:
    build:
      context: src/webapp-backend/
      dockerfile: Dockerfile
    container_name: webapp-backend
    restart: unless-stopped
    ports:
      - "8001:8000"
    environment:
      - TRIPLESTORE_ENDPOINT=http://fuseki:3030/testing
      - PYTHONUNBUFFERED=1
    env_file:
      - .env-backend
  timeseries-parser:
    build: src/timeseries-parser
    container_name: timeseries-parser
    restart: always
    environment:
      - MQTT_BROKER=mqtt-broker
      - MQTT_PORT=1883
      - MQTT_TOPIC=mock-v3/internet-of-soils-playground@ttn/devices/cubecell-1/up
      - FUSEKI_ENDPOINT=http://fuseki:3030/testing/update
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_ORG=bfh
      - INFLUX_BUCKET=default
      - PYTHONUNBUFFERED=1
    env_file:
      - .env-parser
    depends_on:
      - mqtt-broker
      - fuseki
      - influxdb
  mqtt-broker:
    image: eclipse-mosquitto:2.0.21
    container_name: mqtt-broker
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./config/mqtt-broker:/mosquitto/config
      - mqtt-broker-data:/mosquitto/data
      - mqtt-broker-logs:/mosquitto/log
    entrypoint: ["mosquitto", "-c", "/mosquitto/config/mosquitto.conf"]
  fuseki:
    image: stain/jena-fuseki:5.1.0
    container_name: fuseki-triplestore
    restart: unless-stopped
    ports:
      - "3030:3030"
    volumes:
      - fuseki-data:/fuseki
    environment:
      - ENABLE_DATA_WRITE=true
      - ENABLE_UPDATE=true
      - ENABLE_SHACL=false # Used for rdf-structure validation
      - TDB=2
      - FUSEKI_DATASET_1=core # Creates empty dataset with given name
      - FUSEKI_DATASET_2=testing
    env_file:
      - .env-fuseki
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=bfh
      - DOCKER_INFLUXDB_INIT_BUCKET=default
    env_file:
      - .env-influxdb
  ttn-mock:
    build: ./src/ttn-mock
    container_name: ttn-mock
    restart: unless-stopped
    depends_on:
      - mqtt-broker
    environment:
      - MQTT_BROKER=mqtt-broker
      - MQTT_PORT=1883
      - MQTT_TOPIC=mock-v3/internet-of-soils-playground@ttn/devices/cubecell-1/up
      - PUBLISH_INTERVAL_SEC=5
      - PYTHONUNBUFFERED=1

volumes:
  reverse-proxy-conf:
  reverse-proxy-data:
  reverse-proxy-config:
  compiler-engine-source:
    name: compiler-engine-source
  compiler-engine-output:
    name: compiler-engine-output
  compiler-engine-logs:
    name: compiler-engine-logs
  compiler-engine-cache:
    name: compiler-engine-cache
  mqtt-broker-data:
    name: mqtt-broker-data
  mqtt-broker-logs:
    name: mqtt-broker-logs
  fuseki-data:
    name: fuseki-data
  influxdb-data:
    name: influxdb-data
